### ISSUE TITLE
.00 Layout and project settings

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/entertainment-app#1]
### Value Proposition

**As a**  User
 **I need** to see the layout
**to be able** to see the content of the pages

### Acceptance Criteria

- [ ] basic structure and adjustments for the beginning of the project done
- [ ] typografy and colors settings for tailwind are done
- [ ] code quality settings are done
- [ ] project structure according to next13 rules are done

### Tasks

- [ ] create basic structure of the project
- [ ] set up the typography/color settings for tailwind
- [ ] set up code quality
- [ ] set up project structure according to next13 rules

### Sizing/Complexity

**S**
