### ISSUE TITLE
.01 Navbar

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/entertainment-app#3]
### Value Proposition

**As a**  User
 **I need** to navigate between the pages
**to be able** to see the content of the pages

### Description

![Image](https://user-images.githubusercontent.com/110241401/250884563-c4c2d287-0ee7-479a-85fc-69d7a0a96bb7.png)

### Acceptance Criteria

- [ ] navigation bar is fixed at the left side of the screen
- [ ] the  navbar includes 4 links
- [ ] navelements should link to different pages
- [ ] if navelement is active, it should be highlighted (see the picture)
- [ ] logo and profile picture should be seen

### Tasks

- [ ] start creating navigation bar (see picture in the description)
- [ ] link the navelements to the pages
- [ ] create a structure with logo, links, profile picture

### Sizing/Complexity

**S**
